project:
  type: website


website:
  sidebar:
    style: floating
    contents:
      - section: How-To
        contents: guides/*.qmd
      - section: Concepts
        contents: concepts/*.qmd
      - section: Reference
        contents: reference/*.qmd 
               
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd